### PR TITLE
Fix concurrent server process resource contention bugs (and add a test to produce them)

### LINKED ISSUE #251: [Bug]: Potential racey bugs on container-use-state
### What happened?

I've been using claude in parallel pretty aggressively today and encountering transient/probabilistic errors.

the transient one:
```
container-use - environment_run_cmd (MCP)(environment_source: "/Users/braa/src/container-use", command: "grep -n \"environment_id\"
                                             ./mcpserver/args.go", explanation: "Searching for environment_id mentions in args.go")
    Error: failed to update repository: git command failed (exit code 1): exit status 1
    Output: error: cannot lock ref 'refs/notes/container-use-state': is at 42c39e9cc74b4264cf14ac4a68d0a5503240038d but expected
    f9761b0e27d699716039e7d8912ddae75e20e256
    From /Users/braa/.config/container-use/repos/github.com/dagger/container-use
     ! f9761b0..42c39e9  refs/notes/container-use-state -> refs/notes/container-use-state  (unable to update local ref)
```

the random one (this persists for this environment indefinitely and on other tools, too, not just open):
```
container-use - environment_open (MCP)(environment_source: "/Users/braa/src/container-use", environment_id: "vast-coyote", explanation: "Opening
                                        the vast-coyote environment to reproduce the failed file read")
  ⎿  Error: unable to get environment: failed to load state: failed to load state: unexpected end of JSON input
```

### Version

```shell
container-use version
container-use version dev
commit: 7df5adc-dirty
built: 2025-07-23T22:41:45Z
```

### Logs

```text

```

### PR DESCRIPTION
**Pull request by cwlbraa**
fixes #251 and several other bugs surfaced by cmd/container-use/stdio_test.go

This PR adds a test that runs a bunch of actual `container-use stdio` servers in parallel and calls tools on them via an MCP client.

Those tests surfaced a TON of bugs that needed to be fixed via filesystem based locking around the repo's various git states.

~~The test is unfortunately quite slow to run atm (30s), indicating there might be some perf problems added by the locks, but I'd rather have it working and a little slower than regularly broken by data corruption and other failures during concurrent best-of-N claude code usage. tldr; I think this is a critical-enough user story that's hard enough to test that it's worth spending 30s beating on it for every single PR to catch flakes.~~ (i made it way faster using gofrs/flock and RLocks for loadState.)

This PR is intended to go in _before_ single-tenant mode (#246) 

~~I'm a little concerned it's not going to work on windows, please advise @grouville @zhichli.~~

~~I'm also super open to suggestions for dependencies that could be "lighter" replacements for fairly boilerplate AI-generated fslock implementation. maybe https://github.com/gofrs/flock? or https://github.com/rogpeppe/go-internal/tree/master/lockedfile (based on an unreleased stdlib api)~~ (windows and code complexity solved with gofrs/flock)

### CODE REVIEW

File: cmd/container-use/stdio_test.go [hunk 1]
```diff
@@ -0,0 +1,359 @@
...
+			if content == "" {
+				errors[serverIdx] = fmt.Errorf("file read returned empty content")
+				return
+			}
+
+			// Step 4: Run commands to verify the environment works
+			listOutput, err := servers[serverIdx].RunCommand(
+				envID,
+				fmt.Sprintf("ls -la server%d_*.txt | wc -l", serverIdx),
+				"Count files created by this server",
```
Comment (DaggerAssistant) [inline cmd/container-use/stdio_test.go:313]: 🐛 **Bug (Medium):** Potential panic if listOutput is empty - should check array bounds before accessing index 0

```suggestion
lines := strings.Split(strings.TrimSpace(listOutput), "\n")
			if len(lines) == 0 || lines[0] != "3" {
```

File: cmd/container-use/stdio_test.go [hunk 2]
```diff
@@ -0,0 +1,359 @@
...
+	"github.com/stretchr/testify/assert"
+	"github.com/stretchr/testify/require"
+)
+
+// MCPServerProcess represents a running container-use MCP server
+type MCPServerProcess struct {
+	cmd        *exec.Cmd
+	client     *client.Client
+	repoDir    string
+	configDir  string
```
Comment (DaggerAssistant) [inline cmd/container-use/stdio_test.go:24]: 🔧 **Maintainability (Medium):** Build output should be captured for better error diagnostics rather than printing directly to test output

```suggestion
// Capture build output for better test diagnostics
		var stderr, stdout bytes.Buffer
		cmd.Stderr = &stderr
		cmd.Stdout = &stdout
```

File: cmd/container-use/stdio_test.go [hunk 3]
```diff
@@ -0,0 +1,359 @@
...
+	serverInfo *mcp.InitializeResult
+	t          *testing.T
+}
+
```
Comment (DaggerAssistant) [inline cmd/container-use/stdio_test.go:28]: 🐛 **Bug (Medium):** Should include build output in error message for better debugging (requires implementing the stderr/stdout capture suggestion above)

```suggestion
if err != nil {
			t.Fatalf("Failed to build container-use binary: %v\nStderr: %s\nStdout: %s", err, stderr.String(), stdout.String())
		}
```

File: cmd/container-use/stdio_test.go [hunk 4]
```diff
@@ -0,0 +1,359 @@
...
+			return textContent.Text, nil
+		}
+	}
+
+	return "", nil
+}
+
+// Test Cases
+
+func TestSharedRepositoryContention(t *testing.T) {
```
Comment (DaggerAssistant) [inline cmd/container-use/stdio_test.go:205]: 🔧 **Maintainability (Low):** More descriptive skip message would help developers understand why the test is being skipped

```suggestion
if testing.Short() {
		t.Skip("Skipping slow E2E concurrency test")
	}
```

File: repository/fslock.go [hunk 5]
```diff
@@ -0,0 +1,173 @@
...
+
+	// Ensure lock directory exists
+	if err := os.MkdirAll(filepath.Dir(rl.lockFile), 0755); err != nil {
+		return fmt.Errorf("failed to create lock directory: %w", err)
+	}
+
+	// Try to acquire lock with exponential backoff
+	const maxRetries = 30
+	const baseDelay = 50 * time.Millisecond
+	const maxDelay = 2 * time.Second
```
Comment (DaggerAssistant) [inline repository/fslock.go:96]: ⚡ **Performance (Low):** Traditional for loop is clearer for retry logic with exponential backoff calculations

```suggestion
for i := 0; i < maxRetries; i++ {
```

File: repository/fslock.go [hunk 6]
```diff
@@ -0,0 +1,173 @@
...
+
+	for i := range maxRetries {
+		select {
+		case <-ctx.Done():
+			return ctx.Err()
+		default:
+		}
```
Comment (DaggerAssistant) [inline repository/fslock.go:103]: 🔒 **Security (Low):** Lock files should have more restrictive permissions (0600) to prevent other users from reading process information

```suggestion
fd, err := os.OpenFile(rl.lockFile, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0600)
```

File: repository/fslock.go [hunk 7]
```diff
@@ -0,0 +1,173 @@
...
+
+				select {
+				case <-ctx.Done():
+					return ctx.Err()
+				case <-time.After(delay):
+					continue
+				}
+			}
+			return fmt.Errorf("failed to create lock file: %w", err)
+		}
```
Comment (DaggerAssistant) [inline repository/fslock.go:120]: 🐛 **Bug (Medium):** Should handle potential write errors and clean up lock file on failure

```suggestion
if _, err := fmt.Fprintf(fd, "pid:%d\ntime:%s\n", os.Getpid(), time.Now().Format(time.RFC3339)); err != nil {
			fd.Close()
			os.Remove(rl.lockFile)
			return fmt.Errorf("failed to write lock file content: %w", err)
		}
```

File: repository/fslock.go [hunk 8]
```diff
@@ -0,0 +1,173 @@
...
+func (rlm *RepositoryLockManager) WithLock(ctx context.Context, lockType LockType, fn func() error) error {
+	lock := rlm.GetLock(lockType)
+	return lock.WithLock(ctx, fn)
+}
+
+// Lock acquires the repository lock with exponential backoff retry.
+// This prevents multiple processes from performing conflicting git operations simultaneously.
+func (rl *RepositoryLock) Lock(ctx context.Context) error {
+	rl.mu.Lock()
+	defer rl.mu.Unlock()
```
Comment (DaggerAssistant) [inline repository/fslock.go:81]: 🔧 **Maintainability (Low):** Group related constants together for better readability

```suggestion
const (
		maxRetries = 30
		baseDelay  = 50 * time.Millisecond
		maxDelay   = 2 * time.Second
	)
```

File: repository/repository.go [hunk 9]
```diff
@@ -110,34 +112,93 @@ func OpenWithBasePath(ctx context.Context, repo string, basePath string) (*Repos
...
+
+	// Create lock file in parent directory, named after the fork repo
+	lockDir := filepath.Dir(r.forkRepoPath)
+	repoName := filepath.Base(r.forkRepoPath)
+	lockFile := filepath.Join(lockDir, repoName+".lock")
+
+	// Ensure lock directory exists
+	if err := os.MkdirAll(lockDir, 0755); err != nil {
+		return fmt.Errorf("failed to create lock directory: %w", err)
 	}
```
Comment (DaggerAssistant) [inline repository/repository.go:151]: 🐛 **Bug (Medium):** Magic number should be a named constant, and traditional for loop is clearer for retry logic

```suggestion
const maxForkRetries = 10
	for i := 0; i < maxForkRetries; i++ {
```

File: repository/repository.go [hunk 10]
```diff
@@ -110,34 +112,93 @@ func OpenWithBasePath(ctx context.Context, repo string, basePath string) (*Repos
...
+	if _, err := os.Stat(r.forkRepoPath); err == nil {
+		return nil
+	} else if !os.IsNotExist(err) {
+		return err
+	}
+
+	// Create the fork
 	slog.Info("Initializing local remote", "user-repo", r.userRepoPath, "fork-repo", r.forkRepoPath)
 	if err := os.MkdirAll(r.forkRepoPath, 0755); err != nil {
 		return err
```
Comment (DaggerAssistant) [inline repository/repository.go:196]: 🔧 **Maintainability (Medium):** The --template= flag might not be necessary and could cause issues on some Git versions. Consider removing unless specifically needed.

```suggestion
_, err := RunGitCommand(ctx, r.forkRepoPath, "init", "--bare")
```

**Review by DaggerAssistant — COMMENTED** [review]
## 🤖 Code Review

**What this does:** This PR adds comprehensive filesystem-based process locking to prevent concurrent server resource contention bugs when multiple container-use instances operate on the same repository. It introduces a new test suite that runs multiple MCP servers in parallel to reproduce and verify fixes for data corruption issues during concurrent operations.

The implementation addresses a critical concurrency issue by adding granular locking at three levels: repository-level (fork/remote setup), worktree-level (branch creation), and git notes-level (state operations). The locking mechanism uses filesystem locks with exponential backoff retry logic, which is a solid approach for cross-process synchronization. The test suite is well-designed to stress-test concurrent scenarios with 10 parallel servers performing comprehensive workflows. However, there are several areas for improvement: the test has potential for flaky behavior due to hardcoded expectations, the locking implementation could be more robust with timeout handling, and some error handling could be enhanced. The performance concern mentioned by the author is understandable given the added locking overhead, but the trade-off for data integrity is justified.

## 📝 Additional Observations

**🔧 Maintainability (Low)** - `repository/fslock.go`: Consider adding a context timeout to the WithLock method to prevent indefinite blocking. The current implementation could hang if a lock is never released.

**🔧 Maintainability (Low)** - `cmd/container-use/stdio_test.go`: The test creates many temporary directories but relies on t.Cleanup for removal. Consider adding explicit cleanup in case of test panics or early exits.

**⚡ Performance (Low)** - `cmd/container-use/stdio_test.go`: The test uses 10 parallel servers which may be excessive for CI environments. Consider making this configurable via environment variable or reducing the default number.

**🔧 Maintainability (Low)** - `repository/fslock.go`: The hash function for lock file names is simple but could have collisions. Consider using a more robust hashing algorithm or including additional entropy.

**🎨 Style (Low)** - `.gitignore`: The gitignore additions look good for preventing test artifacts and build outputs from being committed.


---
*Generated by DagReview*

File: repository/fslock.go [hunk 11]
```diff
@@ -0,0 +1,173 @@
...
+	const maxDelay = 2 * time.Second
+
+	for i := range maxRetries {
+		select {
+		case <-ctx.Done():
+			return ctx.Err()
+		default:
+		}
+
+		fd, err := os.OpenFile(rl.lockFile, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0644)
```
Comment (cwlbraa) [inline repository/fslock.go]: this is the line that worries me on windows cc @zhichli @grouville

Comment (cwlbraa) [reply repository/fslock.go]: took a dependency on gofrs/flock to avoid this

File: repository/git.go [hunk 12]
```diff
@@ -128,28 +128,34 @@ func (r *Repository) initializeWorktree(ctx context.Context, id string) (string,
...
+		}
+		currentHead = strings.TrimSpace(currentHead)
 
-	_, err = RunGitCommand(ctx, r.forkRepoPath, "worktree", "add", worktreePath, id)
-	if err != nil {
-		return "", err
-	}
+		_, err = RunGitCommand(ctx, r.userRepoPath, "push", containerUseRemote, fmt.Sprintf("%s:refs/heads/%s", currentHead, id))
+		if err != nil {
+			return err
```
Comment (DaggerAssistant) [inline repository/git.go]: 🐛 **Bug (Medium):** Missing error handling after git push command could lead to silent failures in worktree initialization

```suggestion
		_, err = RunGitCommand(ctx, r.userRepoPath, "push", containerUseRemote, fmt.Sprintf("%s:refs/heads/%s", currentHead, id))
		if err != nil {
			return err
		}
```

File: repository/git.go [hunk 13]
```diff
@@ -258,22 +266,34 @@ func (r *Repository) saveState(ctx context.Context, env *environment.Environment
...
 		}
+		result = []byte(buff)
+		return nil
+	})
+
+	if err != nil {
 		return nil, err
 	}
-	return []byte(buff), nil
+	return result, loadErr
```
Comment (DaggerAssistant) [inline repository/git.go]: 🔧 **Maintainability (Low):** Simplify error handling by removing redundant loadErr variable - the err from WithRLock already contains the actual error

```suggestion
func (r *Repository) loadState(ctx context.Context, worktreePath string) ([]byte, error) {
	var result []byte

	err := r.lockManager.WithRLock(ctx, LockTypeGitNotes, func() error {
		buff, err := RunGitCommand(ctx, worktreePath, "notes", "--ref", gitNotesStateRef, "show")
		if err != nil {
			if strings.Contains(err.Error(), "no note found") {
				result = nil
				return nil
			}
			return err
		}
		result = []byte(buff)
		return nil
	})

	return result, err
}
```

File: cmd/container-use/stdio_test.go [hunk 14]
```diff
@@ -0,0 +1,332 @@
...
+// MCPServerProcess represents a running container-use MCP server
+type MCPServerProcess struct {
+	cmd        *exec.Cmd
+	client     *client.Client
+	repoDir    string
+	configDir  string
+	serverInfo *mcp.InitializeResult
+	t          *testing.T
+}
+
```
Comment (DaggerAssistant) [inline cmd/container-use/stdio_test.go:28]: 🐛 **Bug (Medium):** Use t.Skipf instead of t.Fatalf for build failures to avoid stopping the entire test suite when binary compilation fails

```suggestion
		if err != nil {
			t.Skipf("Failed to build container-use binary (required for E2E test): %v", err)
		}
```

File: cmd/container-use/stdio_test.go [hunk 15]
```diff
@@ -0,0 +1,332 @@
...
+	return "", nil
+}
+
+func TestSharedRepositoryContention(t *testing.T) {
+	if testing.Short() {
+		t.Skip("Skipping E2E test")
+	}
+
+	const numServers = 10
```
Comment (DaggerAssistant) [inline cmd/container-use/stdio_test.go:198]: ⚡ **Performance (Low):** Consider reducing the number of concurrent servers from 10 to 5 to improve test execution time while still validating concurrency

```suggestion
	const numServers = 5
```

File: cmd/container-use/stdio_test.go [hunk 16]
```diff
@@ -0,0 +1,332 @@
...
+			repoDir:    sharedRepoDir,
+			configDir:  sharedConfigDir,
+			serverInfo: serverInfo,
+			t:          t,
+		}
+
+		t.Cleanup(func() {
+			servers[i].Close()
+		})
+	}
```
Comment (DaggerAssistant) [inline cmd/container-use/stdio_test.go:244]: 🔧 **Maintainability (Low):** Consider extracting the server creation logic into a helper function to reduce code duplication between NewMCPServerProcess and TestSharedRepositoryContention

File: repository/flock.go [hunk 17]
```diff
@@ -0,0 +1,147 @@
...
+
+	if lock, exists := rlm.locks[lockType]; exists {
+		return lock
+	}
+
+	lockFileName := fmt.Sprintf("container-use-%x-%s.lock", hashString(rlm.repoPath), string(lockType))
+	lockDir := filepath.Join(os.TempDir(), "container-use-locks")
+	lockFile := filepath.Join(lockDir, lockFileName)
+
+	os.MkdirAll(lockDir, 0755)
```
Comment (DaggerAssistant) [inline repository/flock.go]: 🔒 **Security (Low):** Add error handling for MkdirAll to prevent silent failures that could lead to lock file creation issues

```suggestion
	if err := os.MkdirAll(lockDir, 0755); err != nil {
		// Handle error appropriately
	}
```

File: repository/flock.go [hunk 18]
```diff
@@ -0,0 +1,147 @@
...
+}
+
+// hashString creates a simple hash of a string for use in filenames
+func hashString(s string) uint32 {
+	h := uint32(2166136261)
+	for i := 0; i < len(s); i++ {
+		h = (h ^ uint32(s[i])) * 16777619
+	}
+	return h
+}
```
Comment (DaggerAssistant) [inline repository/flock.go]: 🔧 **Maintainability (Low):** Add comments explaining the FNV-1a hash algorithm constants for better code documentation

```suggestion
// hashString creates a simple hash of a string for use in filenames
func hashString(s string) uint32 {
	h := uint32(2166136261) // FNV-1a 32-bit offset basis
	for i := 0; i < len(s); i++ {
		h = (h ^ uint32(s[i])) * 16777619 // FNV-1a 32-bit prime
	}
	return h
}
```

File: cmd/container-use/stdio_test.go [hunk 19]
```diff
@@ -0,0 +1,332 @@
...
+				envID,
+				fmt.Sprintf("ls -la server%d_*.txt | wc -l", serverIdx),
+				"Count files created by this server",
+			)
+			if err != nil {
+				errors[serverIdx] = fmt.Errorf("command execution failed: %w", err)
+				return
+			}
+
+			firstLine := strings.Split(strings.TrimSpace(listOutput), "\n")[0]
```
Comment (DaggerAssistant) [inline cmd/container-use/stdio_test.go]: 🐛 **Bug (Low):** Add bounds checking before accessing slice index to prevent potential panic if command output is empty

```suggestion
			lines := strings.Split(strings.TrimSpace(listOutput), "\n")
			if len(lines) == 0 {
				errors[serverIdx] = fmt.Errorf("command returned empty output")
				return
			}
			firstLine := lines[0]
```

File: repository/repository.go [hunk 20]
```diff
@@ -110,34 +111,39 @@ func OpenWithBasePath(ctx context.Context, repo string, basePath string) (*Repos
...
+			return fmt.Errorf("unable to fork the repository: %w", err)
+		}
+		if err := r.ensureUserRemote(ctx); err != nil {
+			return fmt.Errorf("unable to set container-use remote: %w", err)
+		}
+		return nil
+	})
+	if err != nil {
+		return nil, err
 	}
```
Comment (DaggerAssistant) [inline repository/repository.go:128]: 🔧 **Maintainability (Medium):** The repository initialization logic is now wrapped in a lock, which is good for concurrency safety, but consider adding more descriptive error messages to help distinguish between fork creation and remote setup failures

File: cmd/container-use/stdio_test.go (hunk 14 above)
Comment (cwlbraa) [reply cmd/container-use/stdio_test.go:28]: no (also your diff is wrong)

File: cmd/container-use/stdio_test.go (hunk 15 above)
Comment (cwlbraa) [reply cmd/container-use/stdio_test.go:198]: no, i wanna bully it

File: cmd/container-use/stdio_test.go (hunk 16 above)
Comment (cwlbraa) [reply cmd/container-use/stdio_test.go:244]: agreed, but imma do this later when i add a second test for single-tenant mode

File: repository/flock.go (hunk 17 above)
Comment (cwlbraa) [reply repository/flock.go]: why did you give me only half the suggestion, you're a robot, just write the code plz

File: repository/git.go (hunk 13 above)
Comment (cwlbraa) [reply repository/git.go]: applied by human, this is actually a great catch but the diff is slightly wrong

File: repository/repository.go (hunk 20 above)
Comment (cwlbraa) [reply repository/repository.go:128]: this doesn't make sense

File: repository/git.go (hunk 12 above)
Comment (cwlbraa) [reply repository/git.go]: indent was wrong on this one, but it's a good suggestion

File: repository/repository.go (hunk 20 above)
Comment (cwlbraa) [reply repository/repository.go:128]: @DaggerAssistant this doesn't make sense

**Comment by cwlbraa** [comment]
@aluzzardi meta feedback on the bot responses

> What this does: This PR addresses concurrent server process resource contention bugs by implementing filesystem-based locking around git operations and adding comprehensive E2E tests. The main components include a new RepositoryLockManager using gofrs/flock for process-level synchronization, extensive test coverage with parallel MCP server processes, and protection of critical git operations like worktree initialization, git notes manipulation, and repository setup.

why is it writing the description for me? i guess this is useful for looking back at big PRs with small descriptions?

> The PR effectively tackles a critical concurrency issue that could lead to data corruption when multiple container-use instances operate on the same repository. The locking strategy is well-designed with three granular lock types (repo, worktree, git notes) and uses read/write locks appropriately to balance safety with performance. The E2E test is particularly valuable as it creates realistic concurrent scenarios that would be difficult to reproduce otherwise. However, there are several areas for improvement: error handling could be more robust in some paths, test timeouts might be insufficient for CI environments, and some code patterns could be simplified. The choice of gofrs/flock is appropriate for cross-platform compatibility, and the overall approach demonstrates a solid understanding of the concurrency challenges involved.

tldr; too verbose, and it's mostly just complementing me

🔍 PR-Level Observations

> 🎨 Style (Low): Consider adding package-level documentation explaining the locking strategy and when to use each lock type for better developer experience

I already removed a bunch of LLM-generated comments to this end. LLMs always seem to think it's writing a public library, but for application code the comments are often a hindrance in that they get out-of-date very quickly and are often redescrbiing readable code in english for no reason.

>⚡ Performance (Low): The test creates many temporary directories and git repositories. Consider implementing a test cleanup strategy that runs in parallel or uses a shared test fixture to improve performance

this might actually be true lol, but I like to leave things in /tmp/ after the tests to help with debugging until it becomes a real problem -- aka potentially overengineering

> 🔧 Maintainability (Medium): Consider adding configuration options for lock timeout values instead of hardcoding 100ms retry delays, as different environments may have different performance characteristics

overengineering imo, YAGNI
